### ISSUE TITLE
do you know why I can't access _channels from swift?

### ISSUE THREAD

**Issue by cmario92** [picciano/iOS-Tone-Generator#5]
I have imported the TGSineWaveToneGenerator.h/.m and Xcode automatically bridge the Objective-C files into my swift project.
I have create a new instance ' var generator = TGSineWaveToneGenerator(channels: 2)', but it is not possible to set the frequency, such as generator.channels = xx.

**Comment by picciano** [comment]
Sorry, it's been quite a while since I've looked at this project...

You could either just change the default frequency in the header file if you need a constant frequency, or you could create another init method that takes both the number of channels and frequency. You could even pass in different frequencies for each channel that way.

**Comment by cmario92** [comment]
I used one of your custom constructors to set up the frequency and amplitude, thanks a lot for your rapid reply:)
